# Generated by Django 5.0.6 on 2024-07-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao_id', models.CharField(max_length=255, unique=True)),
                ('nickname', models.CharField(max_length=255)),
            ],
        ),
    ]
