# Generated by Django 5.0.6 on 2024-07-06 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='kakao_id',
            new_name='user_id',
        ),
    ]
