# Generated by Django 5.0.6 on 2024-07-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=255)),
                ('food_category', models.CharField(choices=[('과일', '과일'), ('채소', '채소'), ('쌀/잡곡/견과', '쌀/잡곡/견과'), ('정육', '정육'), ('계란', '계란'), ('수산물', '수산물'), ('유제품', '유제품'), ('밀키트', '밀키트'), ('반찬', '반찬'), ('양념/오일', '양념/오일'), ('생수', '생수'), ('기타', '기타')], max_length=20)),
                ('unit', models.CharField(choices=[('개', '개'), ('ml', 'ml'), ('g', 'g')], max_length=10)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
