# Generated by Django 5.0.6 on 2024-07-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakao', '0002_rename_kakao_id_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
